name: workmanager_example
description: Demonstrates how to use the workmanager plugin.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  http: ^0.13.5
  auto_route: ^5.0.1
  logging: ^1.0.2
  get_it: ^7.2.0
  get_storage: ^2.0.3
  fluttertoast: 8.0.8
  flutter_signin_button: ^2.0.0
  flutter_svg: ^1.1.4
  readmore: ^2.2.0
  json_annotation: ^4.3.0
  flutter_screenutil: ^5.5.4
  flutter_staggered_grid_view: ^0.4.1
  freezed_annotation: ^2.1.0
  flutter_bloc: ^8.1.1
  shimmer: ^2.0.0
  retrofit: ^3.0.1+1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  bot_toast: ^4.0.3
  intl: ^0.17.0
  # shared_preferences: ^2.0.11
  flutter_vector_icons: ^1.0.0
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.2.0
  equatable: ^2.0.5
  loading_overlay: ^0.3.0
  image: ^4.0.17
  carousel_slider: ^4.1.1
  flutter_switch: ^0.3.2
  auto_size_text: ^3.0.0
  syncfusion_flutter_datepicker: ^20.2.48
  video_player: ^2.4.7
  chewie: ^1.3.5
  permission_handler: ^9.2.0
  firebase_core: ^2.1.1
  google_sign_in: ^5.1.0
  firebase_dynamic_links: ^5.0.3
  app_settings: ^4.1.8
  image_picker: ^0.8.5
  share_plus: ^6.2.0
  firebase_messaging: ^14.1.1
  webview_flutter: ^3.0.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  syncfusion_flutter_charts: ^20.3.48
  flutter_datetime_picker: 
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  url_launcher: ^6.1.6
  modal_bottom_sheet:
    git:
      url: https://github.com/bayysp/modal_bottom_sheet.git
      path: modal_bottom_sheet
      ref: 3.0.0-pre+1-idn_version
  badges: ^3.1.0
  mqtt_client: ^9.7.2
  get: ^4.6.5
  dropdown_button2: ^1.8.9
  firebase_auth: ^4.1.2
  device_info_plus: ^8.2.2
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  flutter:
    sdk: flutter
  workmanager: ^0.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  auto_route_generator: ^5.0.2
  retrofit_generator: ^4.0.3+1
  freezed: ^2.1.0+1
  hive_generator: 2.0.0

  
    # path: ../
flutter_icons:
  android : true 
  ios: true
  image_path: "assets/logo.jpeg"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/mubaha_logo/
    - assets/images/logo/
    - assets/images/error/
    - assets/images/category/
    - assets/images/icons/
    - assets/images/bottom/
    - assets/images/splash/
    - assets/translations/
    - assets/data/categories.json
    - assets/data/products.json
    - assets/data/users.json
    - assets/data/homepage.json
    - assets/data/categories.json
    - assets/data/favorite.json
    - assets/data/cartpage.json